name: dio_retry_interceptor
description: "A Dio interceptor that retries failed requests on network reconnection."
version: 0.0.1
homepage: https://github.com/AmanuelDemelash/dio_retry_interceptor
repository: https://github.com/AmanuelDemelash/dio_retry_interceptor
issue_tracker: https://github.com/AmanuelDemelash/dio_retry_interceptor/issues
license: MIT


environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  connectivity_plus: ^5.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.6


flutter:


topics:
  - retry
  - dio
  - http
  - connectivity
  - flutter
  
